### ISSUE TITLE
Can export the default webpack configuration?

### ISSUE THREAD

**Issue by zh2120** [developit/preact-cli#458] opened 2018-01-12 10:46 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
Export a default webpack configuration,  enhanced projects

**If this is a feature request, what is motivation or use case for changing the behaviour?**
advanced-configuration

**Comment by lukeed** [comment] 2018-01-12 23:50
Hi there, unfortunately this (currently) isn't possible. Linking to a good explanation of why: https://github.com/developit/preact-cli/issues/427#issuecomment-353810429

Typically, this is called "ejecting" and there are a few other issues that have asked the same thing. Will be closing this as a duplicate of those (#199, #366, #427). Thanks!

**Closed by lukeed** 2018-01-12 23:50 UTC
Labels: duplicate
