### ISSUE TITLE
Less support is true by default

### ISSUE THREAD

**Issue by abs-zero** [developit/preact-cli#128] opened 2017-06-21 06:19 UTC
The `--less` option is supposed to be`false` by default, but `preact create` creates a project with less support.

**Comment by developit** [comment] 2017-06-21 14:10
The scaffolded project doesn't take `--less` into account, it just copies the directories (which contain less right now).  Closing as a duplicate of #32, let's track progress on context-aware project creation there.

**Closed by developit** 2017-06-21 14:10 UTC
