### ISSUE TITLE
SockJS issue when port is different than 8080

### ISSUE THREAD

**Issue by jpoo90** [developit/preact-cli#345] opened 2017-08-29 00:35 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After executing an AJAX request, this errors from sock start populating the console

![preactsockerror](https://user-images.githubusercontent.com/5958030/29799246-6757427c-8c30-11e7-8fd0-e1b27c9b6643.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

- Run a server on port 8080
- npm start from the preact-cli created project. 
- Use fetch to request something. 
- Sock will start logging errors into the console. 

**What is the expected behavior?**
I think sock should be mapped to the port were the app is running. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version: 8.1.4
- npm version: 5.3.0
- Operating system: osX
- preact-cli: 1.4.1

**Comment by filoxo** [comment] 2017-09-01 21:52
Your server is not actually running on `8080`, which you might be expecting. The CLI will randomly choose a port to run on if 8080 is taken (see the URL in your browser), but there is definitely a bug in that the hmr script isn't using that randomly-selected port. I came here to report this as well.

**Comment by didierfranc** [comment] 2017-10-26 21:53
Same here

**Comment by developit** [comment] 2017-12-25 01:38
Yup - looks like we're not passing port correctly.

**Comment by oieduardorabelo** [comment] 2018-09-13 07:36
hey all 👋, 

I tried to reproduce this bug but seems it is fixed on current stable version,

🐛 💥 🐞 

---
[TEST SCENARIO]

- new file `$ touch same.js` with:
```
const http = require('http');

const PORT = 8080;

const server = http.createServer((req, res) => {
  res.end(`Hello http://localhost:${PORT}!`);
});

server.listen(PORT, () => {
  console.log(`Running on`, server.address())
});
```
- using `$ node same.js`
- new preact project `$ preact create simple testy`
- running `$cd testy` and `$ npm start`, we've:
<img width="646" alt="screen shot 2018-09-13 at 7 30 44 pm" src="https://user-images.githubusercontent.com/829902/45473576-8a188500-b78b-11e8-8c05-0c8bb85b1c8a.png">
<img width="436" alt="screen shot 2018-09-13 at 7 30 48 pm" src="https://user-images.githubusercontent.com/829902/45473582-8e44a280-b78b-11e8-9299-fe3d1c32e78c.png">

- opening it in my browser, Chrome Version 71.0.3544.2 (Official Build) canary (64-bit):
<img width="640" alt="screen shot 2018-09-13 at 7 32 28 pm" src="https://user-images.githubusercontent.com/829902/45473689-d5329800-b78b-11e8-86ac-2a2f48173700.png">

- my `index.js`:

```
import "./style";
import { Component } from "preact";

export default class App extends Component {
  componentDidMount() {
    console.log(`fetch:start`);
    fetch("https://dog.ceo/api/breeds/image/random")
      .then(res => res.json())
      .then(data => {
        console.log(`fetch:done - .then`);
        console.log(data);
      })
      .catch((err) => {
        console.log(`fetch:done - .catch`);
        console.log(err);
      });
  }
  render() {
    return (
      <div>
        <h1>Hello, World!</h1>
      </div>
    );
  }
}
```

- have fun 👍

**Closed** 2019-01-25 23:42 UTC
Labels: bug
