### ISSUE TITLE
npm test doesn't work on newly created project

### ISSUE THREAD

**Issue by yduman** [developit/preact-cli#555] opened 2018-04-17 20:08 UTC
**Do you want to request a *feature* or report a *bug*?**
This is a Bug request.

**What is the current behaviour?**
Running `npm test` on a newly created project with `preact create default myApp` results in

```
$ npm run test

> myapp@0.0.0 test C:\Projects\myApp
> jest ./tests

No tests found
In C:\Projects\myApp
  8 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 1 match
  testPathIgnorePatterns: \\node_modules\\ - 8 matches
Pattern: ./tests - 0 matches

```

**If the current behaviour is a bug, please provide the steps to reproduce.**
- `preact create default myApp`
- `cd myApp`
- `npm test`

**What is the expected behaviour?**
The expected behaviour is, that tests should run without failure.

**Please mention other relevant information.**
- Node v.8.9.4
- NPM v.5.6.0
- OS: Windows 10
- CLI v.2.2.1

**Comment by yduman** [comment] 2018-04-21 19:43
no reactions? 😄 this is actually something, that should work out of the box

**Comment by Panya** [comment] 2018-04-21 20:06
The output clearly says that there are no tests. This is not a bug.

**Comment by yduman** [comment] 2018-04-21 20:54
There are tests automatically generated by the CLI under `src/tests`. The npm command should look inside there but it doesn't.

**Comment by Panya** [comment] 2018-04-21 21:03
It looks like a bug in Jest on Windows. The same command working fine on Mac/Linux.

**Comment by anantoghosh** [comment] 2018-04-25 11:06
Facing the same problem, (on windows)
I got this workaround: 

1. Rename `tests` to `__tests__`
2. Change `setupFiles` path to match
3. Use jest directly from script.

**Comment by anantoghosh** [comment] 2018-04-26 12:48
Running `jest tests` works instead of `jest ./tests` from the cli. @prateekbh would you consider a PR for this.

**Comment by developit** [comment] 2018-04-26 15:07
Seems like the tests directory was supposed to end up at the repo root, but the default template has it in `src/tests`. Personally I'd prefer it at the repo root.  In that setup, we'll have to add this to the package.json "jest" field:

```
"jest": {
  "testRegex": "(/(__tests__|tests)/.*|(\\.|/)(test|spec))\\.jsx?$"
}
```

**Comment by reznord** [comment] 2018-04-26 15:08
I can fix this once I reach home or let's just leave it to the world

**Comment by oieduardorabelo** [comment] 2018-09-12 06:38
i tried to reproduce it locally and seems it is fixed @amitsarangi :

- `$ preact create default testy`
- `$ cd testy`
- `$ npm test`

ran it on VirutalBox with Windows 7, macOS 10.13.6 and Ubuntu 14.04

**Comment by amitsarangi** [comment] 2018-09-12 08:18
@oieduardorabelo Yeah the PR is merged, and this issue can be closed now.

**Closed** 2018-09-12 10:29 UTC
Labels: Good first bug, bug, help wanted
