### ISSUE TITLE
preact create take so long time to finish

### ISSUE THREAD

**Issue by rivajunior** [developit/preact-cli#520] opened 2018-03-04 17:53 UTC
**Do you want to request a *feature* or report a *bug*?**

I want a *feature* because I think that I had a *bug*. So I will first talk about the bug.

**What is the current behaviour?**

The creation of an app don't finish.

**If the current behaviour is a bug, please provide the steps to reproduce.**

`preact create default name --yarn --git --install`  was taking more than two hours. It was take so long that I give up and I was try to delete the generated folder, but I geted the following error `rm: cannot remove 'name/node_modules/simplehttp2server'`': Device or resource busy.

So the bug is the time left to create an app and the impossibility of remove a folder after the creation fails.

**What is the expected behaviour?**

was to create the application with the specified name and install dependencies with the yarn flag, in addition to creating a git repository.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

Would be good loggin the information about process for give an idea about whats going on with the current app creation. Maybe a `--verbose` flag

**Please mention other relevant information.**
- Node version 9.6.1
- npm version 5.6.0
- Operating system Windows 10 Falls Creator Update
- CLI version 2.1.1

**Comment by lukeed** [comment] 2018-03-04 17:56
Sorry to hear! I'd try again with this:

```sh
$ preact create default name --yarn --git --no-install
```

Then run `yarn` yourself manually. This way you'll get the files at least & can restart if needed.

The `simplehttp2server` is a massive dependency and will likely be removed going forward. It can sometimes get stuck based on `npm` permissions. 

That said, you may need `sudo` to install.

**Comment by rivajunior** [comment] 2018-03-04 18:25
Thank you @lukeed, with the `--no-install` flag have worked.

But it seems like an error occurring with installation when I choosie to yarn for manager my dependencies.

With that flag, the only information that appears is `i INFO Assuming you meant preactjs-templates / default.` and stock in that.

My version of yarn is 1.5.1

**Comment by lukeed** [comment] 2018-03-04 18:48
Likely a permissions error. Try `sudo` or just revert to sudo install with npm.

**Comment by rivajunior** [comment] 2018-03-04 22:34
I told before that was worked, but I was just saw the yarn loging and the installetion of dependencies don't work even with npm command.

Since I am on windows, no have a sudo command, but I open windows power shell in administrator mode to execute the `preact` command. It stil not working.

![captura de tela 2](https://user-images.githubusercontent.com/11370172/36951443-b2febfc0-1fe2-11e8-9545-cf83860607aa.png)

the creation do not pass of that

**Comment by developit** [comment] 2018-03-13 14:58
This is a duplicate of #406. `simplehttp2server` is failing to install on your machine.

Try running `npm i -g simplehttp2server`

**Closed** 2018-03-28 04:25 UTC
Labels: duplicate
