### ISSUE TITLE
Preact create sass gives less files

### ISSUE THREAD

**Issue by jrock2004** [developit/preact-cli#109] opened 2017-06-10 20:03 UTC
Just downloaded preact-cli and when I do the following command, the files are .less instead of .scss

```
# preact create test-app --sass
```

Am I doing something wrong?

**Comment by developit** [comment] 2017-06-10 20:40
No, we need to update the templates to automate this. Right now all `--sass` does is install and configure SASS, it doesn't affect the template.  I'll close this out since it's a duplicate of #32.

**Closed by developit** 2017-06-10 20:40 UTC
