### ISSUE TITLE
Initialize git as standard

### ISSUE THREAD

**Issue by jeanleonino** [developit/preact-cli#447] opened 2017-12-27 21:45 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Git is not initialized within a new project. 
 
**If this is a feature request, what is motivation or use case for changing the behavior?**
It is not standard to not use git on a project, having to get into the folder and starting git is just an unnecessary repetitive step that could be avoided. 

Especially considering that preact-cli assumes you are going to use git, since it puts a `.gitignore` file on start.

**Comment by lukeed** [comment] 2017-12-27 22:25
Hi there, there's actually a `--git` flag specifically for this behavior.

**Comment by prateekbh** [comment] 2017-12-27 22:26
probably i see the other side where without `--git` we should not produce a `.gitignore` as well. Or is it coming from the templates?

**Comment by lukeed** [comment] 2017-12-27 22:30
It's from templates.

**Comment by jeanleonino** [comment] 2017-12-29 02:22
@lukeed then shouldn't the `--git` be the one to create the .`gitignore` file? And... Shouldn't `--git` be standard?

**Comment by prateekbh** [comment] 2017-12-29 02:36
sounds legit

**Comment by lukeed** [comment] 2017-12-29 03:06
No. Each template brings with it its own files, file structures, config files, ..., and files to ignore.

As of 2.0, the CLI no longer cares about or manipulates your project contents. That's a template concern.

All we do now is place the contents, provide a build config, run the build, and provide a production server, which is completely optional and, imo, rarely used.

**Comment by lukeed** [comment] 2017-12-29 03:09
I'm going to close this issue because the current setup works as intended and is the result of a previous Community discussion.

In fact, @prateekh I think you were one of the main advocates for removing `git init` as a default behavior and putting it behind a flag instead?

**Comment by jeanleonino** [comment] 2017-12-29 03:10
@lukeed I agree these things are rarely used. But git is not rarely used. Having the `.gitignore` file misleads new users that git is installed and/or configured. This is not cool.

**Comment by jeanleonino** [comment] 2017-12-29 03:10
Could you link the previous community discussion?

**Closed** 2017-12-29 03:09 UTC

**Comment by lukeed** [comment] 2017-12-29 03:20
I don't remember where the discussion took place. I thought it was an issue/PR, but now I'm thinking it was within Slack.

In any event, here's the PR that ended up make this non-default: https://github.com/developit/preact-cli/pull/237

**Comment by jeanleonino** [comment] 2017-12-29 03:23
Since there's no real good reason I will just leave a complain here. Sad to see how some things are handled, especially on a so simple issue.

**Comment by lukeed** [comment] 2017-12-29 03:35
As mentioned on Slack, I personally agree with you. It's just that _because_ it's a breaking change, we wouldn't be able to do this now. It's also the fact that we'd be _reverting_ a previous breaking change, which can't be considered lightly.

Also as mentioned, happy to revisit this again in the future when the timing is more appropriate.

I'm sorry if I came across as dismissive -- not my intention! 😞 I was just trying to give you a quick synopsis of previous debates & why this can't be quick fix. (If it could, I would have done it long time ago! 😉)

I've tagged it with labels to _make sure_ this isn't forgotten during `3.0` discussions, altho I wouldn't have forgotten about it anyhow.

**Comment by prateekbh** [comment] 2017-12-30 01:39
>In fact, @prateekbh I think you were one of the main advocates for removing git init as a default behavior and putting it behind a flag instead?

oh yes yes! I still stand fot it.. And it makes sense what we are doing now. Its just that the entire idea of a project not having `gitignore` without `--git` made sense to me.

**Comment by lukeed** [comment] 2017-12-30 01:40
Ah ok, gotcha 😆
