### ISSUE TITLE
How to pre-render all routes?

### ISSUE THREAD

**Issue by OngeUK** [developit/preact-cli#187] opened 2017-07-04 11:19 UTC
Currently, using the default files that are created upon running `preact create`, when I run a `build` a single `index.html` with pre-render mark-up is generated. What I'm looking for is for all route pages to be generated (after all, not all users will enter the site via the `/index.html` page).

Ideally a `build` would produce the following statically generated pages:

/index.html
/profiles/index.html
/profiles/john/index.html

Is it possible to do this, and if so how?

**Comment by framp** [comment] 2017-07-05 14:01
Duplicate of https://github.com/developit/preact-cli/issues/185

I created a pull request to fix it: https://github.com/developit/preact-cli/pull/192
You may want to give it a go.

I'm using it like this:
https://github.com/framp/framp.github.io/blob/master/src/prerender-urls.json
https://github.com/framp/framp.github.io/blob/master/package.json#L10

**Comment by lukeed** [comment] 2017-07-05 15:53
Closed via #192 🎉

**Closed by lukeed** 2017-07-05 15:53 UTC
