### ISSUE TITLE
Generator functions and async functions

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [developit/preact-cli#586] opened 2018-06-11 11:19 UTC
I know this is a duplicate of #17 but the issue was closed without any fix. So `generator functions` are not supported out of the box, then through that I issue I found out that `async/await` is not also supported leaving me with no choice at all. I'm new to preact and I'm migrating from ReactJS and VueJS. It works while I'm developing:

```
yarn dev
Compiled successfully!

You can view the application in browser.

Local:            http://localhost:8080
On Your Network:  http://ip:8080
```

<img width="1440" alt="screen shot 2018-06-11 at 7 14 19 pm" src="https://user-images.githubusercontent.com/39720421/41228672-b991aa52-6dab-11e8-86f0-4d3fbd6571e7.png">

I see all the console logs from my `root reducer` and `root saga`. That means they work. But `yarn serve` and `yarn build` fails with the following output: (same error with npm)

```
$ preact build && preact serve
✖ ERROR bundle.880ec.js from UglifyJs
Unexpected token operator «*», expected punc «(» [./store/sagas/index.js:3,15][bundle.880ec.js:3907,50]
Build failed! null
error Command failed with exit code 1.
```

```
node: v10.4.0
yarn: 1.7.0
npm: 6.1.0
```

## Note

I'm experiencing this error from `preact create default testapp` which means this is a new with pretty much nothing in it.

## RootSaga

```
import { all } from 'redux-saga/effects';

export default function* () {
  console.log('yow from saga!');

  yield all([

  ]);
}
```

## RootReducer

```
export default (state, action) => {
  console.log('yow from redux', state, action);
};
```

## Babelrc

```
{
  "plugins": [
    "transform-object-rest-spread",
    "transform-regenerator",
    ["transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true
    }]
  ],
  "presets": [
    "env"
  ]
}
```

Please, let's not close this issue without getting an actual fix.

**Comment by sprlwrksAprilmintacpineda** [comment] 2018-06-11 11:37
I found this -> https://github.com/developit/preact-cli-plugin-async which could be helpful to use async await instead of generator functions.

**Comment by lukeed** [comment] 2018-06-11 17:56
Hey, Yeah it's a duplicate of that & #36

This isn't something we want to solve/ship within CLI directly, but is easily achievable thru minimal config changes, as you found.

Supporting generators can also be achieved by adding in the relevant babel plugin(s) to support the syntax. I can't remember which off hand, but I know there are at least 4 options in that arena.

Hope that helps~!

**Comment by sprlwrksAprilmintacpineda** [comment] 2018-06-12 03:39
@lukeed I saw the .babelrc and I thought the CLI already use that, turns out I have to move it to the `root directory` from the `src directory`, but doing so would tell the CLI to use that instead of **append and replace matches** which means now it also does not understand this syntax -> `handleRoute = () =>`. Why not ship the CLI with support for `async/await` and `generator functions` out of the box?

**Comment by developit** [comment] 2018-06-21 13:00
@sprlwrksAprilmintacpineda because the (accurately) transpiled output of async/await and generators is huge and slow. it's a high cost most people don't realize they're paying.

**Comment by sprlwrksAprilmintacpineda** [comment] 2018-06-22 01:47
@developit how slow?

**Closed** 2018-06-25 05:19 UTC
