### ISSUE TITLE
How to mount a preact-cli generated app to a custom div id?

### ISSUE THREAD

**Issue by TarikFojnica** [developit/preact-cli#457] opened 2018-01-06 23:23 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The cli does not allow mounting app to a specific `id`

**If this is a feature request, what is motivation or use case for changing the behavior?**
In some cases, we want to mount an app to a specific `div id=""`. In my case, I already have a static site, but I want to create a part which will be a Preact app. This will preserve the advantages of the static site I have as well as add the new features Preact comes with.

**Comment by tconroy** [comment] 2018-01-09 15:43
dupe of https://github.com/developit/preact-cli/issues/264

have you looked at preact-habitat? might suit your needs. https://github.com/zouhir/preact-habitat

**Comment by developit** [comment] 2018-01-10 15:17
You can also opt-out of preact-cli's automatic rendering - just don't export anything from `src/index.js`:

```js
import App from './components/app';
import { render } from 'preact';

// render into some specific element:
render(<App />, document.getElementById('my-div-id'))
```

**Closed by developit** 2018-01-10 15:17 UTC
