### ISSUE TITLE
Error: Cannot find module 'extract-text-webpack-plugin' with npm@5.2.0

### ISSUE THREAD

**Issue by thangngoc89** [developit/preact-cli#214] opened 2017-07-11 11:35 UTC
```
$ preact -v 
1.3.0

$ npm -v 
5.2.0
```

Error:

```
Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/khoa/web/mui/node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js:13:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/khoa/web/mui/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:39:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/khoa/web/mui/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:27:28)
    at Module._compile (module.js:569:30)
```

Reproduce:

- Init new project `preact create test && cd $_`
- `npm start`

P/s:

This only happens with npm@5.2.0. For some reason, node can't resolve it 

```
❯ npm ls extract-text-webpack-plugin
mui@1.0.0 /home/khoa/web/mui
└─┬ preact-cli@1.3.0
  └─┬ @webpack-blocks/extract-text2@0.4.0
    └── extract-text-webpack-plugin@2.1.2 
```

My rule of thumb is if you use it, you must install it first. Thoughts @developit @lukeed ?

**Comment by reznord** [comment] 2017-07-11 11:41
@thangngoc89 can't able to reproduce.

Might be because during installation of node_modules, something got missed.

Can you try removing node_modules and reinstalling them?

**Comment by thangngoc89** [comment] 2017-07-11 11:47
@reznord I reproduced this twice.

**Comment by thangngoc89** [comment] 2017-07-11 11:50
Apparently, npm installed it but node can't resolve it 

```
❯ npm ls extract-text-webpack-plugin
mui@1.0.0 /home/khoa/web/mui
└─┬ preact-cli@1.3.0
  └─┬ @webpack-blocks/extract-text2@0.4.0
    └── extract-text-webpack-plugin@2.1.2 
```

**Comment by reznord** [comment] 2017-07-11 12:16
Looks like an `npm` issue for me. In 5.0.1, I am not able to reproduce this.

**Comment by slaskis** [comment] 2017-07-11 14:26
Same issue if you try to use [npx](https://www.npmjs.com/package/npx) to create a new app:

```
$ npx preact-cli create test
npx: installed 1 in 12.986s
Cannot find module 'extract-text-webpack-plugin'
```

Which otherwise would be an awesome way to use preact-cli.

**Comment by thangngoc89** [comment] 2017-07-11 14:34
@slaskis Actually it's how I discovered this bug. :D . Wanted to try out npx on npm@5.2.0

**Comment by developit** [comment] 2017-07-11 15:35
sounds like an npm dedupe issue

**Comment by thangngoc89** [comment] 2017-07-11 15:40
@developit My point still stand. We are importing extract-text-webpack-plugin directly in the code, so we should install directly

**Comment by reznord** [comment] 2017-07-11 15:55
I agree with @thangngoc89. Webpack 3 has separated the [plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) totally. I guess it is better to install it separately.

**Comment by thangngoc89** [comment] 2017-07-11 16:00
@reznord Could you make a PR to replace @webpack-blocks/extract-text2 with extra-text-webpack-plugin directly? We dont use `@webpack-blocks/extract-text2` directly anymore.

**Comment by reznord** [comment] 2017-07-11 16:01
@thangngoc89 ayeee... enroute a PR. 😄

**Comment by reznord** [comment] 2017-07-11 16:23
@thangngoc89 we are not using that anywhere as of now. Probably extra bloat I guess. I guess this might be using in the `Complete SSR` PR from @rkostrzewski

**Comment by thangngoc89** [comment] 2017-07-11 16:25
@reznord I'm not follow. We're using extract-text-webpack-plugin but not webpack-block/extract-text2.

**Comment by Connorelsea** [comment] 2017-07-12 05:02
Got this error using the latest NPM, was able to "fix" by simply using yarn instead. For anyone stuck: `yarn global add preact-cli`

**Comment by developit** [comment] 2017-07-17 01:07
^^ Ahh interesting, I didn't realize we had moved off of webpack-blocks for this already. Definitely best to add it as a dependency then.

**Comment by fokusferit** [comment] 2017-07-17 13:36
We also got to the same problem. The current issue rises when we don't install preact-cli globally and use it from the `node_modules`.

**Comment by anantoghosh** [comment] 2017-08-10 10:17
@reznord any pr for the master branch? It has been fixed in the webpack3 branch 79fb4fa9cb89e3ce1f189d38feaf6a235f30f66f

**Comment by reznord** [comment] 2017-08-10 11:12
@anantoghosh webpack3 will be available in the next version (which might take sometime) because there are a bunch of things which we are planning for the next release

**Comment by thangngoc89** [comment] 2017-08-10 15:01
@anantoghosh if you can send a PR to back port that change to preact-cli, I'll be happy to merge it

**Comment by reznord** [comment] 2017-08-10 16:46
I wouldn't do that! Sick it is already changed in webpack branch, that might just lead us to conflicts while merging it.

**Comment by thangngoc89** [comment] 2017-08-10 16:52
@reznord this is a bug and we should fix it asap. Since webpack 3 will be a major change and the release day is pretty much unclear. I would recommend back port the fix and release a new version

**Comment by reznord** [comment] 2017-08-10 16:59
Well, in that case it is fine. (:

**Closed** 2017-08-11 14:15 UTC
Labels: bug, help wanted
