### ISSUE TITLE
Creating projectError: spawn npm ENOENT

### ISSUE THREAD

**Issue by stiks** [developit/preact-cli#470] opened 2018-01-23 08:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Not sure if this is *BUG* or *FEATURE*

**What is the current behaviour?**
NPM is required to install preact using CLI, need an option to use yarn instead of npm or `preact-cli` should detect installed package manager

**If the current behaviour is a bug, please provide the steps to reproduce.**
```
$ preact create default frontend
ℹ INFO Assuming you meant preactjs-templates/default...
⠋ Creating projectError: spawn npm ENOENT
```

No issues if I'll install it by myself:
```
$ cd frontend && yarn install
... 
success Saved lockfile.
Done in 82.35s.
```

**What is the expected behaviour?**
CLI should detect installed package manager and use it. 

**If this is a feature request, what is motivation or use case for changing the behaviour?**
NPM is dying, most of the people already using Yarn. I'm not asking to replace NPM with yarn, but would be good if CLI can detect installed package manager. It's hard to get Node and NPM in sync on Debian 

**Please mention other relevant information.**
- Node version _v8.9.3_
- npm version _not installed_
- Operating system Debian 9
- CLI version _v2.1.1_

**Comment by reznord** [comment] 2018-01-23 08:50
By default, when ever you create a new project using `preact create default my-project`, it configures with `npm`. If you want to create a project using `yarn`, you can pass on the `--yarn` flag i.e. `preact create default my-project --yarn`.

**Comment by stiks** [comment] 2018-01-23 10:11
@lukeed @reznord Would be good if this will appear in `preact help` message as well as checking if npm is available as part of node check (and suggest use `--yarn` option)

**Comment by reznord** [comment] 2018-03-28 04:03
@stiks `preact help` lists out all the commands which CLI has and `preact create help` list all the flags and gives detailed explanation for the same.

**Comment by reznord** [comment] 2018-03-28 04:05
I am not able to reproduce this issue anymore. Please feel free to close this issue if you are still facing the issue.

**Closed by reznord** 2018-03-28 04:05 UTC
