### ISSUE TITLE
preact create exits with status 1

### ISSUE THREAD

**Issue by m4r1vs** [developit/preact-cli#415] opened 2017-10-20 19:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
when creating a new PWA with following command:
`preact create default --name caf-menu --git --force --yarn`
I get this output:
`⚠ WARN Insufficient command arguments! Prompting...`
`ℹ INFO Alternatively, run preact create --help for usage info.`
`? Directory to create the app caf-menu`
`? Install dependencies Yes`
`ℹ INFO Assuming you meant preactjs-templates/default...`
`⠙ Installing dependenciesError: Exited with status 1`

And the created folder-structure looks like this:
caf-menu
- node_modules (contains folders for packages, but they're empty, so node_modules is 0kb)
- src (contains expected files)
- .gitignore
- package.json
- README.md
- yarn-error.log

yarn-error.log looks like this:
```Arguments: 
  /home/Marius/.nvm/versions/node/v8.2.1/bin/node /home/Marius/.nvm/versions/node/v8.2.1/bin/yarn install

PATH: 
  /home/Marius/.nvm/versions/node/v8.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/libnvvp:/mnt/c/Python36/Scripts:/mnt/c/Python36:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files/Geth:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Ruby23-x64/bin:/mnt/c/Users/mariu/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mariu/AppData/Local/atom/bin:/mnt/c/Users/mariu/AppData/Roaming/npm:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/mariu/AppData/Local/Microsoft/WindowsApps:/snap/bin

Yarn version: 
  0.27.5

Node version: 
  8.2.1

Platform: 
  linux x64

npm manifest: 
  {
    "private": true,
    "name": "caf-menu",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "start": "if-env NODE_ENV=production && npm run -s serve || npm run -s dev",
      "build": "preact build",
      "serve": "preact build && preact serve",
      "dev": "preact watch",
      "lint": "eslint src"
    },
    "eslintConfig": {
      "extends": "eslint-config-synacor"
    },
    "eslintIgnore": [
      "build/*"
    ],
    "devDependencies": {
      "eslint": "^4.5.0",
      "eslint-config-synacor": "^1.1.0",
      "if-env": "^1.0.0",
      "preact-cli": "^2.0.0"
    },
    "dependencies": {
      "preact": "^8.2.1",
      "preact-compat": "^3.17.0",
      "preact-router": "^2.5.5"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: EINVAL: invalid argument, lstat '/mnt/c/Users/mariu/Documents/Projects/caf-menu/node_modules/@types/glob/node_modules/@types/node/index.d.ts'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
That the command doesn't exit with an error and works like it did on preact-cli version 1.4

**Please mention other relevant information.**
- node version v8.2.1
- npm version 5.5.1
- yarn version 0.27.5
- Operating system Windows 10 pro 1709 (using Windows Subsystem for Linux)
- Preact-cli version 2.0.1

**Comment by m4r1vs** [comment] 2017-10-20 19:21
After upgrading yarn to v1.2.1 the same bug remains

**Comment by m4r1vs** [comment] 2017-10-20 19:23
See also [this](https://github.com/yarnpkg/yarn/issues/4188) and [this](https://github.com/Microsoft/BashOnWindows/issues/2448) issue on that topic

**Comment by lukeed** [comment] 2017-10-20 20:16
I think #409 might fix this issue.

**Comment by m4r1vs** [comment] 2017-10-20 21:09
No, I don't think so, the name in package.json is correct and I think it's a WSL/YARN realated issue. The only reason it might not be is because it worked before on Preact CLI v1.4

**Comment by ssteinerx** [comment] 2017-10-21 19:32
Not sure if this is related, but I tried to create/install with:

```
preact create--yarn --git --install default ssteinerX-preact
ℹ INFO Assuming you meant preactjs-templates/default...
⠦ Installing dependenciesError: Exited with status 1
```

And the "name" field in package.json was, literally `"{{name}}"` which yarn didn't like at all.

There was no log file, just `package.json` and the `src/` directory.

**Comment by m4r1vs** [comment] 2017-10-21 22:21
Yeah, that's another issue. For now add the --name flag to the Preact create command and the name is correct in package.json :)
I've already corrected this bug and now I'm facing the issue I described above

**Comment by Dylanderv** [comment] 2017-10-25 12:34
Hi, I have the same issue right now with: 
`preact create default new-project`
It give me this:
```
ℹ INFO Assuming you meant preactjs-templates/default...
⠸ Installing dependenciesError: Exited with status 1
```
The `ǹew-project` folder is created with:
- a package.json file:
```json
{
  "private": true,
  "name": "new-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "if-env NODE_ENV=production && npm run -s serve || npm run -s dev",
    "build": "preact build",
    "serve": "preact build && preact serve",
    "dev": "preact watch",
    "lint": "eslint src"
  },
  "eslintConfig": {
    "extends": "eslint-config-synacor"
  },
  "eslintIgnore": [
    "build/*"
  ],
  "devDependencies": {
    "eslint": "^4.5.0",
    "eslint-config-synacor": "^1.1.0",
    "if-env": "^1.0.0",
    "preact-cli": "^2.0.0"
  },
  "dependencies": {
    "preact": "^8.2.1",
    "preact-compat": "^3.17.0",
    "preact-router": "^2.5.5"
  }
}
```
As well as a README.md and a src folder.

If I do a `npm start` it compile well and the app *seems* to work.

I'm a beginner with preact and preact-cli, I'm maybe missing something.

**Comment by reznord** [comment] 2017-10-25 12:37
@Dylanderv are you using the latest version of CLI? `v2.0.2`

**Comment by reznord** [comment] 2017-10-25 12:43
@m4r1vs this is fixed in `v2.0.2`, it works fine, just checked. Thanks for finding this issue. 😄

**Comment by Dylanderv** [comment] 2017-10-25 12:44
@reznord Yes, I'm using `preact-cli@2.0.2`

**Comment by reznord** [comment] 2017-10-25 12:55
@Dylanderv ummm....I just checked it in my machine and it was working fine for me. Can you please give me the steps to reproduce this?

**Comment by Dylanderv** [comment] 2017-10-25 13:03
I'm not doing anything more than `preact create default new-project`.
I first had a problem with my corporate proxy (see #421), but i'm working this around using an external connection without proxy.

I'm using node v8.4.0 and npm 5.3.0 with nvm on Debian stretch.

**Comment by akullpp** [comment] 2017-12-14 14:14
`"lint": "eslint src/ --fix || exit 0"` fixes this.

**Comment by developit** [comment] 2017-12-14 17:20
@Dylanderv are you using Sinopia/Verdaccio by any chance?

**Comment by reznord** [comment] 2018-01-27 18:46
Can't reproduce this in the latest version of CLI (closing for now).

Feel free to re-open if anyone still faces the same issue.

**Closed by reznord** 2018-01-27 18:46 UTC
