### ISSUE TITLE
HMR not working in 2.0.0

### ISSUE THREAD

**Issue by selrond** [developit/preact-cli#400] opened 2017-10-13 06:22 UTC
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
If I change something (component content for example) in my code, I have to do a manual page reload, seems like HMR has stopped working or something

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to change something and see if it refreshes in the browser automatically

**What is the expected behavior?**
The changes are reflected immediately

**Please mention other relevant information.**
- node version: 8.7.0
- npm version: 5.5.1
- Operating system MacOS 10.12.6 (16G29)

**Comment by lukeed** [comment] 2017-10-13 06:54
Hey,

I've spun up a fresh 2.0 app with the `default` template. HMR very much works.

Do you have a `preact.config.js`? Something there might be affecting the setup.

**Comment by selrond** [comment] 2017-10-13 06:56
@lukeed I don't. I've used it out of the box, and suddenly - after I updated to v2.0.0, it's stopped working.

**Comment by lukeed** [comment] 2017-10-13 06:59
I'd wipe everything. Remove `node_modules` and any lock files, then reinstall.

**Comment by selrond** [comment] 2017-10-13 07:11
@lukeed possibly related? [Hot Reloading broke - webpack v3 · Issue #949 · webpack/webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues/949)

**Comment by lukeed** [comment] 2017-10-13 07:19
Update: I was testing a 1.4.1 app, 🤦‍♂️ 

Webpack 3.x is indeed not allowing HMR. I've tested removal of `ModuleConcatenationPlugin` and it had no effect, which I expected, since we're only using it in production builds.

**Comment by reznord** [comment] 2017-10-13 07:39
I just checked with v2.0.0 on a new machine. It works totally fine for me. All the changes what I make in the code are being reflected in the browser as usual.

**Comment by lukeed** [comment] 2017-10-13 08:07
@reznord https://github.com/preactjs-templates/default/blob/master/template/package.json#L21

**Comment by selrond** [comment] 2017-10-13 08:27
@reznord  are you sure you're working with 2.0.0? Check your `package.json`

**Comment by reznord** [comment] 2017-10-13 10:09
Ah, bummer! My bad. So, HRM does fail in latest version. 😞

**Comment by selrond** [comment] 2017-10-13 11:12
@developit Anything we can do about that?

**Comment by rchaubey** [comment] 2017-10-14 13:37
removing `ModuleConcatenationPlugin` from webpack.base.config doesn't solves it.

**Comment by selrond** [comment] 2017-10-16 07:44
@rchaubey yep - exactly what @lukeed [tried](https://github.com/developit/preact-cli/issues/400#issuecomment-336371482)

**Comment by reznord** [comment] 2017-10-16 07:47
@rchaubey changing to 1.4.1 works because we are on webpack 2.x in v1.4.1 in which the HMR works without any problem.

**Comment by selrond** [comment] 2017-10-16 08:00
Let's hope @developit will jump in ASAP

**Comment by reznord** [comment] 2017-10-16 08:07
I was talking to Sean about the same and he said similar issue was reported in vue-cli as well for the same HMR.

The issue is in the html-webpack-plugin. Once it is fixed in the upstream, probably a minor release with version upgrade for CLI should be good.

**Comment by reznord** [comment] 2017-10-21 19:45
#417 has a temporary fix for this until it is fixed in `webpack-dev-server`, thanks @zouhir

**Closed by reznord** 2017-10-21 19:45 UTC
