### ISSUE TITLE
Packages using custom process variables not working

### ISSUE THREAD

**Issue by conblem** [developit/preact-cli#269] opened 2017-07-28 08:29 UTC
Hey together

I just tried to use ```react-instantsearch``` with your awesome preact-cli.
This gave me an ```process is not defined``` error.
I easily got rid of it using the ```preact.config.js``` method with the following file:
```javascript
import { DefinePlugin } from 'webpack';

export default function(config, env, helpers) {
	config.plugins.push(
		new DefinePlugin({
			process: {
				env: {}
			}
		})
	);
}
```

But i thought this would be easily fixable by just changing this line:
https://github.com/developit/preact-cli/blob/c706900b53718968931cde0833c8ac7ef48c35ae/src/lib/webpack/webpack-base-config.js#L240

Im not sure if this is a general problem, what do you guys think?
I would gladly submit a pull request if it makes sense.

**Comment by lukeed** [comment] 2017-09-18 15:11
I'm sorry none of us got back to you -- I missed it somehow! 🙈 

It happens to be a duplicate of #244, which has a fix mentioned:

```js
// preact.config.js
export default config => {
  config.node.process = 'mock';
}
```

Sorry again, but hope that's still of some help~!

**Closed by lukeed** 2017-09-18 15:11 UTC

**Comment by Haroenv** [comment] 2017-12-02 14:31
Small note here, what you wrote was not a valid arrow function, I found it slightly more readable in a function (arrow function requires you to make a const somewhere before exporting)

```js
export default function(config) {
  config.node.process = 'mock';
}
```

**Comment by conblem** [comment] 2017-12-03 14:55
@Haroenv i am pretty sure that it is infact a correct arrow function ;)

**Comment by Haroenv** [comment] 2017-12-03 15:46
yep, it's correct, I wrote something wrong originally when I commented
